language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry install
script:
  - black --check -v nvelope/ tests/
  - mypy .
  - pytest --cov nvelope/ --cov-report xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
